version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - APP_URL=http://localhost:8082
    networks:
      - app-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - PORT=8082
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge